title: Randall Smith
description: Personal Site on GitHub.
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
og_image: "./assets/images/Homer-simpson-brain.jpg"
author:
  name   : "Your Name"
  avatar : "bio-photo.jpg"  # placed in /images/
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : # optional
  uri    : "http://your-site.com"
